CREATE TABLE PUBLIC."USER"
(ID INTEGER NOT NULL,
USERNAME VARCHAR(25),
PRIMARY KEY (ID));
INSERT INTO PUBLIC."USER" (ID, USERNAME) VALUES (1, 'A');
INSERT INTO PUBLIC."USER" (ID, USERNAME) VALUES (2, 'B');
INSERT INTO PUBLIC."USER" (ID, USERNAME) VALUES (3, 'C');
INSERT INTO PUBLIC.FULLNAME (ID, FIRSTNAME, LASTNAME, ACCOUNT_FK) VALUES (1, 'a', 'a', 1);
INSERT INTO PUBLIC.FULLNAME (ID, FIRSTNAME, LASTNAME, ACCOUNT_FK) VALUES (2, 'b', 'b', 2);
INSERT INTO PUBLIC.FULLNAME (ID, FIRSTNAME, LASTNAME, ACCOUNT_FK) VALUES (3, 'c', 'c', 3);