CREATE TABLE PUBLIC."USER"
(ID INTEGER NOT NULL,
USERNAME VARCHAR(25),
PRIMARY KEY (ID));
INSERT INTO PUBLIC."USER" (ID, USERNAME) VALUES (1, 'A');
INSERT INTO PUBLIC."USER" (ID, USERNAME) VALUES (2, 'B');
INSERT INTO PUBLIC."USER" (ID, USERNAME) VALUES (3, 'C');